import { Character } from './types';

export const CHARACTERS: Character[] = [
  {
    id: 'luffy',
    name: 'Monkey D. Luffy',
    source: 'One Piece',
    color: 'from-orange-500 to-red-600',
    glowColor: 'rgba(239, 68, 68, 0.9)',
    avatarEmoji: '👒',
    avatarImage: 'https://miro.medium.com/0*j7sVnq-dE0XWdS12.jpeg',
    message: "OI ADITYA! YOU'RE 20 NOW! SHISHISHI! Let's eat meat and party till the whole sea hears us!! I'm gonna be King of the Pirates and YOU'RE gonna have the best birthday EVER!",
    styleType: 'luffy',
    auraCss: 'shadow-[0_0_35px_rgba(239,68,68,0.7)] animate-pulse border-red-500/80',
    constellationPosition: { x: -30, y: -30 }
  },
  {
    id: 'eragon',
    name: 'Eragon Shadeslayer',
    source: 'The Inheritance Cycle',
    color: 'from-cyan-400 to-blue-600',
    glowColor: 'rgba(59, 130, 246, 0.9)',
    avatarEmoji: '🐉',
    avatarImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7JCMSOszfHSxga2I9C9Bs5aI60aAXxN9deA&s',
    message: "May your twentieth year bring you the strength of a Rider, the wisdom of the elves, and the courage to face whatever dragons life sends your way. Sé onr sverdar sitja hvass, Aditya.",
    styleType: 'eragon',
    auraCss: 'shadow-[0_0_35px_rgba(59,130,246,0.7)] border-blue-500/80',
    constellationPosition: { x: -16, y: -44 }
  },
  {
    id: 'ben',
    name: 'Ben Tennyson',
    source: 'Ben 10',
    color: 'from-green-400 to-emerald-600',
    glowColor: 'rgba(16, 185, 129, 0.9)',
    avatarEmoji: '⌚',
    avatarImage: 'https://i.redd.it/m371t6qs40eb1.jpg',
    message: "Dude, you're 20! That's like... hero level age. If I had an alien for every awesome year you've lived, I'd have 20 new forms. It's Hero Time, Aditya — go live it!",
    styleType: 'ben',
    auraCss: 'shadow-[0_0_35px_rgba(16,185,129,0.7)] border-emerald-500/80',
    constellationPosition: { x: 16, y: -44 }
  },
  {
    id: 'koro',
    name: 'Koro-Sensei',
    source: 'Assassination Classroom',
    color: 'from-yellow-300 to-yellow-500',
    glowColor: 'rgba(234, 179, 8, 0.9)',
    avatarEmoji: '🎓',
    avatarImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuda9CRtaaqG6EAlt9B5MqVNoPikS-AgQYwA&s',
    message: "Nuhuhuhu~ My most exceptional student, Aditya, has reached 20 years! I always knew you'd outgrow being a teenager. The world better prepare itself — your assassination of mediocrity begins NOW!",
    styleType: 'koro',
    auraCss: 'shadow-[0_0_35px_rgba(234,179,8,0.7)] border-yellow-400/80',
    constellationPosition: { x: 30, y: -30 }
  },
  {
    id: 'ayanokoji',
    name: 'Ayanokoji Kiyotaka',
    source: 'Classroom of the Elite',
    color: 'from-slate-400 to-zinc-600',
    glowColor: 'rgba(148, 163, 184, 0.8)',
    avatarEmoji: '♟️',
    avatarImage: 'https://miro.medium.com/1*ERRIYEfRZETF1Ng4aHIoYA.jpeg',
    message: "Turning 20 is simply the beginning of a longer game. You have calculated correctly by making it this far, Aditya. ...Happy Birthday. Don't make a scene about it.",
    styleType: 'ayanokoji',
    auraCss: 'shadow-[0_0_30px_rgba(148,163,184,0.6)] border-slate-400/60',
    constellationPosition: { x: -38, y: -3 }
  },
  {
    id: 'spiderman',
    name: 'Spider-Man',
    source: 'Your Friendly Neighbor',
    color: 'from-blue-500 via-red-500 to-blue-600',
    glowColor: 'rgba(239, 68, 68, 0.9)',
    avatarEmoji: '🕷️',
    avatarImage: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?w=300&auto=format&fit=crop&q=80',
    message: "HEY! Happy Birthday Aditya!! Twenty years old — with great age comes great responsibility! But also... great parties. You've totally earned this one. Your friendly neighborhood Spider-Man is PROUD of you!",
    styleType: 'spiderman',
    auraCss: 'shadow-[0_0_35px_rgba(239,68,68,0.7)] border-red-500/80',
    constellationPosition: { x: 38, y: -3 }
  },
  {
    id: 'batman',
    name: 'Batman',
    source: 'The Dark Knight',
    color: 'from-stone-800 to-stone-900',
    glowColor: 'rgba(31, 41, 55, 0.95)',
    avatarEmoji: '🦇',
    avatarImage: 'https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=300&auto=format&fit=crop&q=80',
    message: "Aditya. Twenty years old. I've studied your journey. Your resilience is... noted. The city is safer with people like you in it. Don't waste this decade. Happy Birthday.",
    styleType: 'batman',
    auraCss: 'shadow-[0_0_40px_rgba(251,191,36,0.3)] border-amber-500/40',
    constellationPosition: { x: -32, y: 24 }
  },
  {
    id: 'robin',
    name: 'Robin',
    source: 'Teen Titans',
    color: 'from-green-600 via-red-500 to-yellow-500',
    glowColor: 'rgba(245, 158, 11, 0.9)',
    avatarEmoji: '⭐',
    avatarImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSy4ej6jPwm8IozXYVJEaYZqSTzEgHXnPTSRg&s',
    message: "TITANS, ATTENTION! Today we celebrate Aditya turning 20! As leader of the Teen Titans I officially declare today a HOLIDAY! You've always been one of us, and that never changes. TITANS GO!!",
    styleType: 'robin',
    auraCss: 'shadow-[0_0_35px_rgba(16,185,129,0.7)] border-yellow-400/70',
    constellationPosition: { x: 32, y: 24 }
  },
  {
    id: 'krishna',
    name: 'Shri Krishna',
    source: 'Divine Presence',
    color: 'from-amber-400 via-teal-400 to-amber-500',
    glowColor: 'rgba(234, 179, 8, 1)',
    avatarEmoji: '🪶',
    avatarImage: 'https://galleryofgod.wordpress.com/wp-content/uploads/2014/03/lord-krishna-new.jpg',
    message: "Dear Aditya, you carry the same name as the eternal sun. At 20, remember — the soul neither ages nor diminishes. Act with love, live with dharma, and know that I have always walked beside you. Shubh Janmadin.",
    styleType: 'krishna',
    auraCss: 'shadow-[0_0_45px_rgba(234,179,8,0.9)] border-amber-400',
    constellationPosition: { x: 0, y: -52 }
  },
  {
    id: 'tomjerry',
    name: 'Tom & Jerry',
    source: 'Classic Companions',
    color: 'from-slate-400 to-amber-700',
    glowColor: 'rgba(244, 63, 94, 0.85)',
    avatarEmoji: '🐱',
    avatarImage: 'https://ihavenothingtowatch.home.blog/wp-content/uploads/2021/03/tom-jerry.jpg',
    message: "Even rivals agree — Aditya deserves the best birthday.",
    styleType: 'tomjerry',
    auraCss: 'shadow-[0_0_35px_rgba(244,63,94,0.6)] border-rose-400/80',
    constellationPosition: { x: -16, y: 44 }
  },
  {
    id: 'bean',
    name: 'Mr. Bean',
    source: 'An Adequatest Birthday',
    color: 'from-yellow-800 to-amber-950',
    glowColor: 'rgba(120, 113, 108, 0.8)',
    avatarEmoji: '🧸',
    avatarImage: 'https://i.pinimg.com/564x/f6/d1/14/f6d11405b92c9393da6dde525f0aeefa.jpg',
    message: "Mr. Bean and Teddy wish you a very, very... adequate birthday. (That's the highest compliment he gives.)",
    styleType: 'bean',
    auraCss: 'shadow-[0_0_30px_rgba(202,138,4,0.5)] border-stone-500/60',
    constellationPosition: { x: 16, y: 44 }
  }
];
